// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ8bckTmrFnVXHih1QtmD4sEV-ENbepgk',
    appId: '1:456220183612:web:1a98ab7ebcd3ae33ea4739',
    messagingSenderId: '456220183612',
    projectId: 'fcm4flutter-a3ef9',
    authDomain: 'fcm4flutter-a3ef9.firebaseapp.com',
    storageBucket: 'fcm4flutter-a3ef9.firebasestorage.app',
    measurementId: 'G-C69Z46SMZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmqugpLu91WpLRB-Y-0tNs0p9jigiHKbo',
    appId: '1:456220183612:android:a171c8c869aa7381ea4739',
    messagingSenderId: '456220183612',
    projectId: 'fcm4flutter-a3ef9',
    storageBucket: 'fcm4flutter-a3ef9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDtHlTjp3-ZaEeVuO-j21wpAY6swLVVEg',
    appId: '1:456220183612:ios:cf4ceb05b1d40d49ea4739',
    messagingSenderId: '456220183612',
    projectId: 'fcm4flutter-a3ef9',
    storageBucket: 'fcm4flutter-a3ef9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotification1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDtHlTjp3-ZaEeVuO-j21wpAY6swLVVEg',
    appId: '1:456220183612:ios:cf4ceb05b1d40d49ea4739',
    messagingSenderId: '456220183612',
    projectId: 'fcm4flutter-a3ef9',
    storageBucket: 'fcm4flutter-a3ef9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotification1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ8bckTmrFnVXHih1QtmD4sEV-ENbepgk',
    appId: '1:456220183612:web:67229e7fc2dfc87aea4739',
    messagingSenderId: '456220183612',
    projectId: 'fcm4flutter-a3ef9',
    authDomain: 'fcm4flutter-a3ef9.firebaseapp.com',
    storageBucket: 'fcm4flutter-a3ef9.firebasestorage.app',
    measurementId: 'G-NQ9GSFSLYE',
  );
}
